### ISSUE TITLE
카드만들기

### ISSUE THREAD

**Issue by semihumanbeing** [yhn032/TEKA#24]

**Comment by cloud0990** [comment]
1. div박스 추가해서 카드 만들기 추가
2. 카드 만들기 전에 필요한 정보(c_idx, s_name) 등 필요한 view 생성 (nsertCard)
3.  전에 연결해놨던 만들기 페이지 삭제 -> 새로 구성 중

다음 업데이트 예정 항목
1. q_question / q_answer 서버로 전송하기
2. 학습세트 DB추가
3. div 행 삭제 오류 수정

**Comment by cloud0990** [comment]
card / mycardset / qna 테이블 insert 완료

카드만들기 후, 내 학습세트 조회하는 페이지 연결 -> myCardSet.jsp
해당 페이지 구현은 아직 안 함
