### ISSUE TITLE
좋아요기능

### ISSUE THREAD

**Issue by semihumanbeing** [yhn032/TEKA#47]

**Comment by cloud0990** [comment]
1. 유저 한명 당, 카드 하나에 1회만 추천할 수 있음.
-> DB에 저장되는 l_like의 값은 0 or 1 (눌렀거나, 안 눌렀거나)


+) 추천 여부에 따른 이모티콘 변경 기능 추가 예정

**Comment by semihumanbeing** [comment]
https://github.com/yhn032/TEKA/pull/56
like 오류수정 resVo가 null일때 테이블 추가하게 만듬
학습세트에 추가 할때마다 알림이 나오지 않도록 변경
