### ISSUE TITLE
나도 만들어보기(튜토리얼)

### ISSUE THREAD

**Issue by semihumanbeing** [yhn032/TEKA#9]

**Comment by cloud0990** [comment]
화면 구성 진행 중
main 페이지에서 '나도 만들어보기' 버튼 클릭 시 Action -> test.jsp 파일 이동

**Comment by cloud0990** [comment]
튜토리얼 두 번째 항목 
카드 내용을 길게 입력했을 때, 카드 범위 초과됨

**- 월요일 회의 후 수정 예정입니다.**
